name = "pufffstationvendorssa"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://jtpifraxtevpxqyryacg.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cGlmcmF4dGV2cHhxeXJ5YWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2ODAxNTAsImV4cCI6MjA4MzA0MDE1MH0.U1FygpYYnnhXqlNvwb2Wf2AfiVo8Yp-HA15h91fQ0pI"
NEXT_PUBLIC_SITE_URL = "https://pufffstationsa.co.za"
NEXT_PUBLIC_ADMIN_EMAILS = "pufffstationvendors@gmail.com, disawe542@gmail.com"